import React from "react";
import useTitle from "../../Hooks/useTitle";

const Blog = () => {
  useTitle("Blog")
  return (
    <div className="mx-24 my-10">
      <div className="grid grid-cols-1 gap-5">
        <div
          tabIndex={0}
          className="collapse collapse-arrow border border-base-300 bg-stone-300 rounded-box"
        >
          <div className="collapse-title text-xl font-medium">
           What is access token and refresh token ? The working process and their storage location in  client side of a website
          </div>
          
          <div className="collapse-content flex flex-col gap-2">
            <p>Access tokens are short-lived tokens that are used to access protected resources. They are typically generated by the authorization server and are passed to the third-party application by the user.</p>
            <p>Refresh tokens are long-lived tokens that are used to obtain new access tokens. They are typically generated by the authorization server and are stored by the third-party application. </p>
            <p>When a user logs in to an authorization server, they are given the option to grant a third-party application permission to access protected resources. If the user grants permission, the authorization server generates an access token and a refresh token. The access token is given to the user, while the refresh token is stored by the authorization server. The user then passes the access token to the third-party application. The third-party application uses the access token to access protected resources. When the access token expires, the third-party application can use the refresh token to obtain a new access token from the authorization server. The user does not need to log in again to obtain a new access token.</p>
            <p>The storage location of access tokens and refresh tokens on the client side of a website depends on the type of website and the security requirements of the website. In general, access tokens should be stored in a secure location, such as a browser cookie or a local storage object. </p>

          </div>
        </div>
        <div
          tabIndex={0}
          className="collapse collapse-arrow border border-base-300 bg-stone-300 rounded-box"
        >
          <div className="collapse-title text-xl font-medium">
           Comparison between SQL and NoSQL data base
          </div>
          
          <div className="collapse-content flex flex-col gap-2">
            <p> SQL and NoSQL are two different types of databases. SQL databases are the traditional type of database, while NoSQL databases are a newer type of database that are designed to store and manage large amounts of unstructured data.</p>
            <p>SQL databases use a relational data model, which stores data in tables. Each table has a set of columns and rows. The columns define the data types that can be stored in each row, and the rows store the actual data. SQL is a standard query language that is used to interact with SQL databases. SQL allows you to select, insert, update, and delete data from tables</p>
            <p>NoSQL databases use a variety of data models, including documents, key-value pairs, graphs, and wide columns. Documents are similar to rows in a SQL table, but they can store more complex data structures. Key-value pairs store data as a key and a value. Graphs store data as a network of nodes and edges. Wide columns store data in columns, but each column can have a different data type.</p>

          </div>
        </div>
        <div
          tabIndex={0}
          className="collapse collapse-arrow border border-base-300 bg-stone-300 rounded-box"
        >
          <div className="collapse-title text-xl font-medium">
          what is nest js and express js           </div>
          
          <div className="collapse-content flex flex-col gap-2">
            <p> NestJS is built on top of ExpressJS, so it can be used to create the same types of applications as ExpressJS. NestJS provides a number of additional features that can make development faster and easier.</p>
            <p>ExpressJS is a popular choice for building simple and lightweight web applications. It is easy to learn and use, and there are a large number of resources available to help developers get started. However, ExpressJS does not provide as many features as NestJS, so it may not be the best choice for building complex or enterprise-level applications.</p>
            
          </div>
        </div>
        <div
          tabIndex={0}
          className="collapse collapse-arrow border border-base-300 bg-stone-300 rounded-box"
        >
          <div className="collapse-title text-xl font-medium">
          what is mongodb aggregate and how does it work ?  </div>
          
          <div className="collapse-content flex flex-col gap-2">
            <p> 
MongoDB aggregation is a process of transforming data from a collection into a more meaningful form. It is used to perform operations such as grouping, filtering, and aggregating data.</p>
            <p> The aggregate function takes a pipeline as its main argument, which consists of a sequence of stages. Each stage represents a specific operation to be performed on the data. These stages can include filtering, grouping, sorting, projecting, and transforming the data in various ways. The pipeline stages are processed sequentially, with the output of one stage serving as the input for the next. This allows for a flexible and efficient way of manipulating data within MongoDB, enabling users to extract valuable insights and perform advanced computations on their collections.</p>
            
          </div>
        </div>
      </div>
    </div>
  );
};

export default Blog;
